extends "res://tests/support/test_case.gd"

const NarrativeState = preload("res://game/narrative/state/narrative_state.gd")
const ConditionEvaluator = preload("res://game/narrative/conditions/condition_evaluator.gd")
const EffectExecutor = preload("res://game/narrative/effects/effect_executor.gd")

func run() -> void:
	var state := NarrativeState.new()
	state.set_flag(&"sandwich_more", true)
	state.set_stat(&"corruption", 2.0)
	assert_true(ConditionEvaluator.matches({"kind":"flag", "key":"sandwich_more", "operator":"eq", "value":true}, state), "flag condition")
	assert_true(ConditionEvaluator.matches({"kind":"flag", "key":"sandwich_more", "operator":"neq", "value":false}, state), "flag inequality condition")
	assert_true(ConditionEvaluator.matches({"kind":"stat", "key":"corruption", "operator":"gte", "value":2}, state), "numeric condition")
	assert_true(ConditionEvaluator.matches({"kind":"stat", "key":"corruption", "operator":"gt", "value":1}, state), "numeric greater than condition")
	assert_true(ConditionEvaluator.matches({"kind":"stat", "key":"corruption", "operator":"lt", "value":3}, state), "numeric less than condition")
	assert_true(ConditionEvaluator.matches({"kind":"stat", "key":"corruption", "operator":"lte", "value":2}, state), "numeric less than or equal condition")
	assert_eq(EffectExecutor.apply({"kind":"stat_add", "key":"corruption", "value":1}, state), OK, "effect succeeds")
	assert_eq(state.get_stat(&"corruption"), 3.0, "effect mutates state")
	assert_eq(EffectExecutor.apply({"kind":"inventory_add", "key":"sandwich", "value":2}, state), OK, "inventory add succeeds")
	assert_true(ConditionEvaluator.matches({"kind":"inventory", "key":"sandwich", "operator":"gte", "value":2}, state), "inventory condition")
	assert_eq(EffectExecutor.apply({"kind":"inventory_remove", "key":"sandwich", "value":1}, state), OK, "inventory remove succeeds")
	assert_eq(state.inventory["sandwich"], 1.0, "inventory removal mutates quantity")
	assert_eq(EffectExecutor.apply({"kind":"quest_set", "key":"lunch", "value":"started"}, state), OK, "quest set succeeds")
	assert_true(ConditionEvaluator.matches({"kind":"quest", "key":"lunch", "operator":"eq", "value":"started"}, state), "quest condition")
	assert_eq(EffectExecutor.apply({"kind":"collectible_add", "key":"recipe", "value":1}, state), OK, "collectible add succeeds")
	assert_true(ConditionEvaluator.matches({"kind":"collectible", "key":"recipe", "operator":"contains", "value":true}, state), "collectible possession condition")
	var before_invalid_effect := state.snapshot()
	assert_false(ConditionEvaluator.matches({"kind":"stat", "key":"corruption", "operator":"contains", "value":"2"}, state), "unsupported condition combination is rejected")
	assert_eq(EffectExecutor.apply({"kind":"stat_add", "key":"corruption", "value":"1"}, state), ERR_INVALID_DATA, "invalid effect value is rejected")
	assert_eq(EffectExecutor.apply({"kind":"call", "key":"set_flag", "value":"state.set_flag(&'unsafe', true)"}, state), ERR_INVALID_DATA, "unsupported effect kind is rejected")
	assert_eq(state.snapshot(), before_invalid_effect, "invalid effects do not mutate state")
